import { proxy, wrap } from 'comlink'
import { typescriptDescriptor } from '@typarium/analyzer-typescript/descriptor'
import sampleSnapshot from '#/adapters/typescript/sample-snapshot.gen.json'
import type { Remote } from 'comlink'
import type { AnalysisWorkerApi } from '#/adapters/typescript/analysis.worker.ts'
import type {
  BootProgressEvent,
  LanguageAdapter,
} from '@typarium/language-adapter'
import type { AnalysisResult } from '@typarium/set-model'

/**
 * Main-thread face of the TypeScript adapter: the pure-data descriptor
 * plus a thin comlink proxy to the analysis worker (ADR-0007's
 * LanguageAdapter boundary, capability shape per ADR-0019).
 */
export function createTypescriptAdapter(): LanguageAdapter {
  const worker = new Worker(new URL('./analysis.worker.ts', import.meta.url), {
    type: 'module',
    name: 'ts-analysis',
  })
  const remote: Remote<AnalysisWorkerApi> = wrap<AnalysisWorkerApi>(worker)

  // The worker exposes ONE callback slot per event; the adapter fans
  // out to real multi-subscriber sets so a second listener never
  // silently replaces the first.
  const typesListeners = new Set<() => void>()
  const bootListeners = new Set<(event: BootProgressEvent) => void>()
  void remote.onTypesAcquired(
    proxy(() => {
      for (const listener of typesListeners) listener()
    }),
  )
  void remote.onBootProgress(
    proxy((event: BootProgressEvent) => {
      for (const listener of bootListeners) listener(event)
    }),
  )

  let warmupPromise: Promise<void> | null = null

  return {
    descriptor: {
      ...typescriptDescriptor,
      // Build-time snapshot of the sample's analysis (generated by
      // scripts/generate-sample-snapshot.mts from the same TS pin).
      sampleAnalysis: sampleSnapshot as unknown as AnalysisResult,
    },

    analyze: (source, virtualTypes) => remote.analyze(source, virtualTypes),
    check: (source) => remote.check(source),

    editor: {
      quickInfo: (source, offset) => remote.quickInfo(source, offset),
      completions: (source, offset, preferences) =>
        remote.completions(source, offset, preferences),
      format: (source, options) => remote.format(source, options),
      inlineQueries: (source) => remote.inlineQueries(source),
    },

    onTypesAcquired: (listener) => {
      typesListeners.add(listener)
      return () => typesListeners.delete(listener)
    },
    onBootProgress: (listener) => {
      bootListeners.add(listener)
      return () => bootListeners.delete(listener)
    },
    warmup: () => {
      warmupPromise ??= remote.warmup()
      return warmupPromise
    },

    dispose: () => worker.terminate(),
  }
}
